// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gplmodels

type NewStatus struct {
	State  string `json:"State"`
	Redis  string `json:"Redis"`
	Uptime string `json:"Uptime"`
}

type Status struct {
	State  string `json:"State"`
	Redis  string `json:"Redis"`
	Uptime string `json:"Uptime"`
}
